use_frameworks!

platform :ios, '9.0'

target 'MTWebKitComponent_Example' do
  pod 'MTWebKitComponent', :path => '../'

  target 'MTWebKitComponent_Tests' do
    inherit! :search_paths

    
  end
end
